version: '3.6'
services:
  myapp:
    container_name: hr-management_myapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my_db:3306/mydb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - my_db
    networks:
      - esnet
  my_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: pass
      # Password for root access
      MYSQL_ROOT_PASSWORD: pass
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - esnet
# Names our volume
volumes:
  my-db:
networks:
  esnet:


#version: '3.7'
#services:
#  myapp:
#    container_name: hr-management_myapp
#    build:
#      context: . # Use an image built from the specified dockerfile in the app directory.
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    environment:
#      - JAVA_OPTS=
#        -DDB_SERVER=jdbc:mysql://my_db:3306/my_db?serverTimezone=UTC
#    ports:
#      - 8082:8080
#    depends_on:
#      - my_db
#
#  my_db:
#    container_name: my_db
#    restart: unless-stopped
#    image: mysql
#    volumes:
#      - ./data:/var/lib/mysql
#    ports:
#      - 63306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_PASSWORD=password
#      - MYSQL_USER=user
#      - MYSQL_DATABASE=my_db
